export const styles = {
    app: 'flex',
    menuContainer: 'fixed text-sm p-4',
    input: 'cursor-pointer mr-1',
    inputPrice: 'border-black border rounded-sm mx-1 w-40',
    title: 'font-bold my-3',
    formContainer: 'flex flex-col my-2',
    contentContainer: 'flex flex-col ml-64 w-full items-center',
    cardContainer: 'flex flex-col w-160 flex-grow text-lg my-5',
    formItem: 'flex items-center font-light',
    formItemPrice: 'flex items-center my-1.5',
    cardHeader: 'flex flex-col items-end flex-grow bg-taskBlue text-white px-3 py-1',
    cardPrice: 'text-2xl',
    cardHeaderText: 'text-xs -mt-1',
    cardBlueTime: `mx-2 text-base text-taskBlue`,
    cardButton: 'bg-taskYellow text-white p-2 mt-1',
    cardTime: 'flex mx-2 justify-between text-xl mt-4 mb-1',
    cardBlueText: 'text-base mx-1 text-taskBlue',
    cardDestination: 'm-2',
    cardDuration: 'text-lg mt-1',
    cardCarrier: 'text-base m-2',
    cardLineSm:'h-px w-5/6 bg-gray-400 self-center',
    cardTransfersWrapper:'flex relative h-6 items-center justify-center',
    cardTransfers:'absolute bg-white py-1 px-2 text-base text-taskYellow',
    cardBlueLine: 'h-2px w-full bg-taskBlue',
    showMore: 'bg-gray-200 py-1 px-16 my-6 border-black border'
}